#!/bin/tcsh


@ OutN = 10
set DataFileName = "DpDataDbg.f51"

@ IdOffSet = 180
set ExtraCut = "L_dp_0";
set InvExtraCut = "\!$ExtraCut";

# Events to Opt
@ Id = 0
tree2ascii -vp -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $ExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1170.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1170.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1170.root

@ Id += $IdOffSet
tree2ascii -vpa -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $ExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1172.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1172.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1172.root

@ Id += $IdOffSet
tree2ascii -vpa -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $ExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1181.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1181.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1181.root

@ Id += $IdOffSet
tree2ascii -vpa -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $ExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1183.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1183.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1183.root

@ Id += $IdOffSet
tree2ascii -vpa -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $ExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1190.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1190.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1190.root ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1191.root

# Events as bkgd

@ Id += $IdOffSet
tree2ascii -vpa -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $InvExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1170.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1170.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1170.root

@ Id += $IdOffSet
tree2ascii -vpa -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $InvExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1172.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1172.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1172.root

@ Id += $IdOffSet
tree2ascii -vpa -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $InvExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1181.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1181.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1181.root

@ Id += $IdOffSet
tree2ascii -vpa -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $InvExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1183.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1183.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1183.root

@ Id += $IdOffSet
tree2ascii -vpa -O $Id -N $OutN -f 1.10e -d DpVars.def \
	-C $InvExtraCut \
	-c ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1190.root.SieveCut.cut \
	-g ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1190.root.FullCut.root \
	-o ArchivedRootFiles/SieveCentralLHRS/$DataFileName \
	ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1190.root  ArchivedRootFiles/SieveCentralLHRS/apex_coinc_1191.root


echo "Done!"


