#!/bin/tcsh


################################################

@ IdOffSet = 1
@ Id = 0
@ OutN = 1000000
# @ OutN = 10

set DataFileName = "VertexData.f51"


################################################
# LHRS Iter 1
################################################


# echo "# 1945 : Ta @ $Id"
# tree2ascii -p -O $Id -N $OutN -d VertexVarsBended.def \
# 	-c ArchivedRootFiles/VertexLHRS/apex_coinc_1945.root.VertexCut.cut \
# 	-g ArchivedRootFiles/VertexLHRS/apex_coinc_1945.root.FullCut.root \
# 	-o ArchivedRootFiles/VertexLHRS/${DataFileName} \
# 	ArchivedRootFiles/VertexLHRS/apex_coinc_1945.root
# 
# @ Id += $IdOffSet
# echo "# 1949 : Multi-C @ $Id"
# tree2ascii -ap -O $Id -N $OutN -d VertexVarsBended.def \
# 	-c ArchivedRootFiles/VertexLHRS/apex_coinc_1949.root.VertexCut.cut \
# 	-g ArchivedRootFiles/VertexLHRS/apex_coinc_1949.root.FullCut.root \
# 	-o ArchivedRootFiles/VertexLHRS/${DataFileName} \
# 	ArchivedRootFiles/VertexLHRS/apex_coinc_1949.root


################################################
# RHRS Iter 1
################################################

# echo "# 1945 : Ta @ $Id"
# tree2ascii -p -O $Id -N $OutN -d VertexVarsBended.RHRS.def \
# 	-c ArchivedRootFiles/VertexRHRS/apex_coinc_1945.root.VertexCut.cut \
# 	-g ArchivedRootFiles/VertexRHRS/apex_coinc_1945.root.FullCut.root \
# 	-o ArchivedRootFiles/VertexRHRS/${DataFileName} \
# 	ArchivedRootFiles/VertexRHRS/apex_coinc_1945.root
# 
# @ Id += $IdOffSet
# echo "# 1949 : Multi-C @ $Id"
# tree2ascii -ap -O $Id -N $OutN -d VertexVarsBended.RHRS.def \
# 	-c ArchivedRootFiles/VertexRHRS/apex_coinc_1949.root.VertexCut.cut \
# 	-g ArchivedRootFiles/VertexRHRS/apex_coinc_1949.root.FullCut.root \
# 	-o ArchivedRootFiles/VertexRHRS/${DataFileName} \
# 	ArchivedRootFiles/VertexRHRS/apex_coinc_1949.root

################################################
# RHRS Iter 2
################################################

echo "# 1945 : Ta @ $Id"
tree2ascii -p -O $Id -N $OutN -d VertexVarsBended.RHRS.def \
	-c ArchivedRootFiles/VertexRHRS/apex_coinc_1945.root.VertexCut.cut \
	-g ArchivedRootFiles/VertexRHRS/apex_coinc_1945.root.FullCut.root \
	-o ArchivedRootFiles/VertexRHRS/${DataFileName} \
	ArchivedRootFiles/VertexRHRS/apex_coinc_1945.root

@ Id += 1
echo "# 1949 : 0% Multi-C @ $Id"
tree2ascii -ap -O $Id -N $OutN -d VertexVarsBended.RHRS.def \
	-c ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine1.root.VertexCut.cut \
	-g ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine1.root.FullCut.root \
	-o ArchivedRootFiles/VertexRHRS/${DataFileName} \
	ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine1.root 

@ Id += 3
echo "# 1949 : -2% Multi-C @ $Id"
tree2ascii -ap -O $Id -N $OutN -d VertexVarsBended.RHRS.def \
	-c ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine2.root.VertexCut.cut \
	-g ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine2.root.FullCut.root \
	-o ArchivedRootFiles/VertexRHRS/${DataFileName} \
	ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine2.root 

@ Id += 3
echo "# 1949 : -3.5% Multi-C @ $Id"
tree2ascii -ap -O $Id -N $OutN -d VertexVarsBended.RHRS.def \
	-c ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine3.root.VertexCut.cut \
	-g ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine3.root.FullCut.root \
	-o ArchivedRootFiles/VertexRHRS/${DataFileName} \
	ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine3.root 
	
@ Id += 3
echo "# 1949 : 2% Multi-C @ $Id"
tree2ascii -ap -O $Id -N $OutN -d VertexVarsBended.RHRS.def \
	-c ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine4.root.VertexCut.cut \
	-g ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine4.root.FullCut.root \
	-o ArchivedRootFiles/VertexRHRS/${DataFileName} \
	ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine4.root 
	
@ Id += 3
echo "# 1949 : +3.5% Multi-C @ $Id"
tree2ascii -ap -O $Id -N $OutN -d VertexVarsBended.RHRS.def \
	-c ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine5.root.VertexCut.cut \
	-g ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine5.root.FullCut.root \
	-o ArchivedRootFiles/VertexRHRS/${DataFileName} \
	ArchivedRootFiles/VertexRHRS/apex_coinc_1949.kine5.root 



echo "Done!"


