#!/bin/tcsh

# @ IdOffSet = 180
# @ Id = 0
@ OutN = 100000000
# @ OutN = 10


set Run_number = "4771"

#set baseRootFileName = "/scratch/johnw/apex/Rootfiles/apex_online_"

set baseRootFileName = "/w/work3/home/johnw/Rootfiles/apex_"


set RootFileName_1 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_4771_13_12_19/${Run_number}_replay.root"; 



echo "$RootFileName_1"


set DataFileName = "text_cuts/4771_4774_6_1_20_5th_foil.dat"


set CutSieveFile_1 = "Cuts_Sieve/apex_4771_27_11_2019.root.SieveCut_ell.cut"


set RootFileName_1_c = "${baseRootFileName}${Run_number}_27_11_2019.root"



# Use new graphical cuts for foil 5 that were saved in a different location


set CutSieveFile_1_alt = "Cuts_Sieve/apex_4771_27_11_2019.root.SieveCut_ell.cut_4_5_for_foil_5"


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1_alt \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1 



set RootFileName_1_1 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_4771_13_12_19/${Run_number}_replay_1.root"; 

tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1_alt \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1_1 


set RootFileName_1_2 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_4771_13_12_19/${Run_number}_replay_2.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1_alt \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1_2

set RootFileName_1_3 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_4771_13_12_19/${Run_number}_replay_3.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1_alt \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1_3


set RootFileName_1_4 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_4771_13_12_19/${Run_number}_replay_4.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1_alt \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1_4 





echo "Done!"
