#!/bin/tcsh

# @ IdOffSet = 180
# @ Id = 0
@ OutN = 100000000
# @ OutN = 10




#set baseRootFileName = "/scratch/johnw/apex/Rootfiles/apex_online_"

set baseRootFileName = "/w/work3/home/johnw/Rootfiles/apex_"


set DataFileName = "text_cuts/4771_4774_10_1_20_Foil_6.dat"



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# For Run 4774 (Optics 1 Foils 0,2,4,6)
set Run_number = "4774"


set RootFileName_2_c = "${baseRootFileName}${Run_number}_27_11_2019.root"




#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# For Foil 6, cuts made with a new DB
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


set CutSieveFile_2 = "Cuts_Sieve/apex_4774_27_11_2019.root.SieveCut_ell.cut_10_1_20"


set RootFileName_2 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_9_1_20_Old_Y/${Run_number}_replay.root"; 



echo "$RootFileName_2"


echo "$RootFileName_2_c.FullCut.root_10_1_2"



tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_10_1_20 \
    -o $DataFileName \
    $RootFileName_2 



set RootFileName_2_1 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_9_1_20_Old_Y/${Run_number}_replay_1.root"; 

tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_10_1_20 \
    -o $DataFileName \
    $RootFileName_2_1 


set RootFileName_2_2 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_9_1_20_Old_Y/${Run_number}_replay_2.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_10_1_20 \
    -o $DataFileName \
    $RootFileName_2_2

set RootFileName_2_3 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_9_1_20_Old_Y/${Run_number}_replay_3.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_10_1_20 \
    -o $DataFileName \
    $RootFileName_2_3


set RootFileName_2_4 = "/w/work3/home/johnw/Rootfiles/Correlations/TP_9_1_20_Old_Y/${Run_number}_replay_4.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_10_1_20 \
    -o $DataFileName \
    $RootFileName_2_4 




echo "Done!"
