#!/bin/tcsh

# @ IdOffSet = 180
# @ Id = 0
@ OutN = 100000000
# @ OutN = 10


set Run_number = "4771"

#set baseRootFileName = "/scratch/johnw/apex/Rootfiles/apex_online_"

set baseRootFileName = "/w/work3/home/johnw/Rootfiles/apex_"


set RootFileName_1 = "/w/work3/home/johnw/Rootfiles/Correlations/27th_new_op_V3.dat/${Run_number}_replay.root"; 



echo "$RootFileName_1"


set DataFileName = "text_cuts/Optics_3_phi_v_y_cuts.dat"


#set CutSieveFile = "Cuts_Sieve/apex_4179_26_11_2019.root.SieveCut_ell.cut"




set RootFileName_1_c = "${baseRootFileName}${Run_number}_27_11_2019.root"


tree2ascii -p -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $RootFileName_1_c.VertexCut.cut \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1 



set RootFileName_1_1 = "/w/work3/home/johnw/Rootfiles/Correlations/27th_new_op_V3.dat/${Run_number}_replay_1.root"; 

tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $RootFileName_1_c.VertexCut.cut \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1_1 


set RootFileName_1_2 = "/w/work3/home/johnw/Rootfiles/Correlations/27th_new_op_V3.dat/${Run_number}_replay_2.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $RootFileName_1_c.VertexCut.cut \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1_2

set RootFileName_1_3 = "/w/work3/home/johnw/Rootfiles/Correlations/27th_new_op_V3.dat/${Run_number}_replay_3.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $RootFileName_1_c.VertexCut.cut \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1_3


set RootFileName_1_4 = "/w/work3/home/johnw/Rootfiles/Correlations/27th_new_op_V3.dat/${Run_number}_replay_4.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $RootFileName_1_c.VertexCut.cut \
    -g $RootFileName_1_c.FullCut.root \
    -o $DataFileName \
    $RootFileName_1_4 


echo "Done!"
