#!/bin/tcsh

# @ IdOffSet = 180
# @ Id = 0
@ OutN = 100000000
# @ OutN = 10




#set baseRootFileName = "/scratch/johnw/apex/Rootfiles/apex_online_"

set baseRootFileName = "/w/work3/home/johnw/Rootfiles/apex_"


set DataFileName = "text_cuts/4771_4774_9_1_20.dat"



# For run 4771 


set Run_number = "4771"


set RootFileName_1_c = "${baseRootFileName}${Run_number}_27_11_2019.root"



# For run 4771 Foils 1,3	    

set RootFileName_1 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay.root"; 

echo "$RootFileName_1"


set CutSieveFile_1 = "Cuts_Sieve/apex_4771_27_11_2019.root.SieveCut_ell.cut_15_12_19"



tree2ascii -p -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_15_12_19 \
    -o $DataFileName \
    $RootFileName_1 



set RootFileName_1_1 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay_1.root"; 

tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_15_12_19 \
    -o $DataFileName \
    $RootFileName_1_1 


set RootFileName_1_2 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay_2.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_15_12_19 \
    -o $DataFileName \
    $RootFileName_1_2

set RootFileName_1_3 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay_3.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_15_12_19 \
    -o $DataFileName \
    $RootFileName_1_3


set RootFileName_1_4 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay_4.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_15_12_19 \
    -o $DataFileName \
    $RootFileName_1_4 





# Use new graphical cuts for foil 5 that were saved in a different location


set CutSieveFile_1 = "Cuts_Sieve/apex_4771_27_11_2019.root.SieveCut_ell.cut_9_1_20"

set RootFileName_1 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay.root"; 


echo "$RootFileName_1"


echo "$RootFileName_1_c.FullCut.root_9_1_2"


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_1 



set RootFileName_1_1 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay_1.root"; 

tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_1_1 


set RootFileName_1_2 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay_2.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_1_2

set RootFileName_1_3 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay_3.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_1_3


set RootFileName_1_4 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay_4.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_1 \
    -g $RootFileName_1_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_1_4 




#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# For Run 4774 (Optics 1 Foils 0,2,4,6)
set Run_number = "4774"


set RootFileName_2_c = "${baseRootFileName}${Run_number}_27_11_2019.root"


    
# For Foils 0 and 2 


set RootFileName_2 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay.root"; 


set CutSieveFile_2 = "Cuts_Sieve/apex_4774_27_11_2019.root.SieveCut_ell.cut_15_12_19"


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_6_1_20 \
    -o $DataFileName \
    $RootFileName_2 



set RootFileName_2_1 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay_1.root"; 

tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_6_1_20 \
    -o $DataFileName \
    $RootFileName_2_1 


set RootFileName_2_2 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay_2.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_6_1_20 \
    -o $DataFileName \
    $RootFileName_2_2

set RootFileName_2_3 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay_3.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_6_1_20 \
    -o $DataFileName \
    $RootFileName_2_3


set RootFileName_2_4 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y/${Run_number}_replay_4.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_6_1_20 \
    -o $DataFileName \
    $RootFileName_2_4 




# For Foil 4, cuts made with a new DB


set CutSieveFile_2 = "Cuts_Sieve/apex_4774_27_11_2019.root.SieveCut_ell.cut_9_1_20"

set RootFileName_2 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay.root"; 



echo "$RootFileName_2"


echo "$RootFileName_2_c.FullCut.root_9_1_2"



tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_2 



set RootFileName_2_1 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay_1.root"; 

tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_2_1 


set RootFileName_2_2 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay_2.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_2_2

set RootFileName_2_3 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay_3.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_2_3


set RootFileName_2_4 = "/w/work3/home/johnw/Rootfiles/Correlations/TPY_4771_4774_15_12_19_Silv_old_Y_foil5_test_3_4_all_foils/${Run_number}_replay_4.root"; 


tree2ascii -ap -N $OutN -d Ascii_Variables/SieveVars.def \
    -c $CutSieveFile_2 \
    -g $RootFileName_2_c.FullCut.root_9_1_20 \
    -o $DataFileName \
    $RootFileName_2_4 




echo "Done!"
